nodeLinker: pnp

npmScopes:
  RideSaver:
    npmAlwaysAuth: true
    npmAuthToken: "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"
    npmRegistryServer: "https://npm.pkg.github.com/"

packageExtensions:
  "@RideSaver/api@*":
    peerDependencies:
      "@types/react": "*"
      "@types/react-dom": "*"
      react: "*"
    peerDependenciesMeta:
      "@types/react":
        optional: true
      "@types/react-dom":
        optional: true
      "react-dom":
        optional: true
  "@lingui/macro@*":
    peerDependencies:
      react: "*"
  "@react-native-aria/combobox@*":
    dependencies:
      react-dom: "*"
  "@rushstack/eslint-patch@*":
    dependencies:
      "@eslint/eslintrc": "*"
  "@types/babel__core@*":
    peerDependencies:
      "@babel/generator": "*"
  "@types/hoist-non-react-statics@*":
    peerDependencies:
      react: "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/react-native@*":
    peerDependencies:
      react: "*"
      react-native: "*"
  "@types/react@*":
    dependencies:
      scheduler: "*"
    peerDependencies:
      prop-types: "*"
    peerDependenciesMeta:
      prop-types:
        optional: true
  babel-preset-expo@*:
    peerDependencies:
      "@babel/core": "*"
  eslint-config-react-app@*:
    dependencies:
      "@eslint/eslintrc": "*"
  native-base@*:
    peerDependencies:
      csstype: "*"
    peerDependenciesMeta:
      csstype:
        optional: true
  react-dev-utils@*:
    dependencies:
      babel-plugin-named-asset-import: "*"
      babel-preset-react-app: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-dotenv.cjs
    spec: "https://unpkg.com/yarn-plugin-dotenv/bundles/@yarnpkg/plugin-dotenv.js"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.3.1.cjs
