nodeLinker: pnp

npmScopes:
  RideSaver:
    npmRegistryServer: "https://npm.pkg.github.com/"
    npmAuthToken: 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

packageExtensions:
  "@lingui/macro@*":
    peerDependencies:
      react: "*"
  "@react-native-aria/combobox@*":
    dependencies:
      react-dom: "*"
  "@rushstack/eslint-patch@*":
    dependencies:
      "@eslint/eslintrc": "*"
  "@types/react@*":
    dependencies:
      scheduler: "*"
    peerDependencies:
      prop-types: "*"
    peerDependenciesMeta:
      prop-types:
        optional: true
  "@types/babel__core@*":
    peerDependencies:
      "@babel/generator": "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/react-native@*":
    peerDependencies:
      react: "*"
      react-native: "*"
  "@types/hoist-non-react-statics@*":
    peerDependencies:
      react: "*"
  babel-preset-expo@*:
    peerDependencies:
      "@babel/core": "*"
  eslint-config-react-app@*:
    dependencies:
      "@eslint/eslintrc": "*"
  react-dev-utils@*:
    dependencies:
      babel-plugin-named-asset-import: "*"
      babel-preset-react-app: "*"
  native-base@*:
    peerDependencies:
      csstype: "*"
    peerDependenciesMeta:
      csstype:
        optional: true
  "@RideSaver/api@*":
    peerDependencies:
      react: "*"
      "@types/react": "*"
      "@types/react-dom": "*"
    peerDependenciesMeta:
      "@types/react":
        optional: true
      "@types/react-dom":
        optional: true
      
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.3.1.cjs
