apiVersion: v1
kind: Service
metadata:
    name: ui-server
    namespace: ui
    labels:
        type: rendering-server
spec:
    ports:
        - port: 80
          name: http
        - port: 443
          name: https
    selector:
        type: rendering-server
