# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy to GCP

on:
    push:
        branches:
            - "main"
        tags:
            - "v*"
    release:
        types:
            - published
    workflow_dispatch:
jobs:
    build:
        name: Push Docker image to GitHub Container Registry
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                  platforms: arm,arm64,amd64
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                  platforms: linux/arm,linux/arm64,linux/x64
            - name: Log in to Github Container Repository
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      ghcr.io/ridesaver/ui_server
                  tags: |
                      type=schedule,pattern=nightly
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
                      type=sha
            - name: Build
              uses: docker/bake-action@v2
              with:
                  files: |
                      ./docker-bake.hcl
                      ${{ steps.meta.outputs.bake-file }}
                  targets: build
                  set: |
                      *.args.github_username=${{ github.actor }}
                      *.args.github_token=${{ secrets.GITHUB_TOKEN }}
                  push: true
    deployment:
        name: Deploy
        runs-on: ubuntu-latest
        needs:
            - build

        permissions:
            contents: "read"
            id-token: "write"
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
        steps:
            - uses: actions/checkout@master
            - name: "auth"
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: ${{ secrets.GKE_AUTH_JSON }}
            - id: "get-credentials"
              uses: "google-github-actions/get-gke-credentials@v1"
              with:
                  cluster_name: ${{ secrets.GKE_CLUSTER }}
                  location: 'us-central1'

            - name: Delete old registry secret
              run: kubectl delete secret ridesaver-registry-credentials --ignore-not-found
            - name: Add registry secret
              run: kubectl create secret docker-registry ridesaver-registry-credentials --docker-server=ghcr.io --docker-username=${{ github.actor }} --docker-password=${{ secrets.GITHUB_TOKEN }}
            - name: Trigger deploy
              run: kubectl apply -f kubernetes
